services:
  app_price_alert_web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_PRICE_ALERT_API_URL: ${NEXT_PUBLIC_PRICE_ALERT_API_URL}
    image: nextjs-app:latest
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
